#############################################################################
##
##  complex-reflection.tst -- exercises the SGV_*ComplexReflectionSubgroup
##  helpers on W(E6).  Print booleans and small integers only.
##
gap> START_TEST( "complex-reflection.tst" );

gap> W := SGV_Group( "WE6" );;
gap> s := GeneratorsOfGroup( W );;

##  W(E6) has 36 reflections, and they are exactly the rank-1 ones.
gap> Length( SGV_ReflectionSet( W ) );
36
gap> id := One( W );;
gap> ForAll( SGV_ReflectionSet( W ), g -> RankMat( g - id ) = 1 );
true

##  W is a reflection group; so is the A2 generated by two simple reflections;
##  the C3 they generate together is not; the trivial group vacuously is.
gap> SGV_IsComplexReflectionSubgroup( W, W );
true
gap> SGV_IsComplexReflectionSubgroup( W, Subgroup( W, [ s[1], s[3] ] ) );
true
gap> SGV_IsComplexReflectionSubgroup( W, Group( s[1] * s[3] ) );
false
gap> SGV_IsComplexReflectionSubgroup( W, Group( id ) );
true

##  A list of generating matrices is accepted in place of a group.
gap> SGV_IsComplexReflectionSubgroup( W, [ s[2], s[4] ] );
true

##  The assertion helper returns true on a pass and a diagnostic record on a
##  failure; the record reports the smaller reflection subgroup found.
gap> SGV_AssertIsComplexReflectionSubgroup( W, Subgroup( W, [ s[1], s[3] ] ) );
true
gap> info := SGV_AssertIsComplexReflectionSubgroup( W, Group( s[1] * s[3] ) );;
gap> [ info.isComplexReflectionGroup, info.order, info.nrReflections,
>      info.orderOfReflectionSubgroup ];
[ false, 3, 0, 1 ]

gap> STOP_TEST( "complex-reflection.tst" );
