#############################################################################
##
##  group-theory.gd
##
##  Reusable group-theory utilities that are not tied to any one paper claim.
##  Claim-specific assertion helpers live in gap/checks/; this file is for the
##  plumbing they (and interactive work) are built on.
##

#! The unique subgroup of index 2 in <A>G</A>, or <C>fail</C> if <A>G</A> has
#! no such subgroup or more than one.
#!
#! Subgroups of index 2 are normal and correspond to the nonzero homomorphisms
#! <M>G \to C_2</M>, i.e. to the nonzero vectors of <M>Q/Q^2</M> where
#! <M>Q = G/G'</M> is the abelianisation.  If that space has rank <M>d</M>
#! there are exactly <M>2^d - 1</M> subgroups of index 2, so a unique one
#! exists iff <M>d = 1</M> iff <M>[Q : Q^2] = 2</M>.  In that case <M>Q^2</M>
#! is that subgroup, whose preimage in <A>G</A> is generated by <M>G'</M>
#! together with the squares of the generators of <A>G</A> -- so no subgroup
#! enumeration is needed.
DeclareGlobalFunction( "SGV_UniqueIndexTwoSubgroup" );
