#############################################################################
##
##  complex-reflection.gd
##
##  Is a subgroup G of a real reflection group W again a reflection group in
##  the reflection representation?
##
##  W(E6) and W(E7) act on their reflection representations over Q, so a
##  pseudo-reflection there has a rational non-trivial eigenvalue and is
##  therefore an honest reflection (eigenvalue -1).  Hence
##
##      G is a complex reflection group  <=>  G is generated by the honest
##                                            reflections of W it contains,
##
##  and the whole test needs no root-system data, only the reflections of W.
##

#! The reflections of <A>W</A> -- the matrices <M>g</M> with
#! <M>\mathrm{rank}(g - 1) = 1</M> -- computed as the union of the conjugacy
#! orbits of the generators of <A>W</A>.  This is the complete set exactly when
#! every generator of <A>W</A> is a reflection and every reflection of <A>W</A>
#! is <A>W</A>-conjugate to a generator; both hold for a finite Coxeter group
#! presented by its simple reflections whose Coxeter diagram is connected
#! (E6, E7, ...).  An error is raised if some generator is not a reflection.
#! Stored as an attribute, so the orbit computation happens once per group.
DeclareAttribute( "SGV_ReflectionSet", IsMatrixGroup );

#! <C>true</C> iff <A>G</A> is generated by the reflections of <A>W</A> it
#! contains, i.e. iff <A>G</A> is a complex reflection group in the reflection
#! representation of <A>W</A>.  <A>G</A> is a subgroup of <A>W</A>, or a list of
#! matrices generating one.  The trivial group is generated by the empty set of
#! reflections and counts as <C>true</C>.
DeclareGlobalFunction( "SGV_IsComplexReflectionSubgroup" );

#! The computation behind <Ref Func="SGV_IsComplexReflectionSubgroup"/>, as a
#! record: <C>isComplexReflectionGroup</C>, <C>order</C> of <A>G</A>,
#! <C>nrReflections</C> of <A>W</A> lying in <A>G</A>,
#! <C>orderOfReflectionSubgroup</C> they generate, that
#! <C>reflectionSubgroup</C> itself, and its <C>structure</C>.  Use it when the
#! answer is <C>false</C> and you want to see how far <A>G</A> is from being
#! generated by its reflections.
DeclareGlobalFunction( "SGV_ReflectionSubgroupInfo" );

#! Claim helper: <A>G</A> is a complex reflection group in the reflection
#! representation of <A>W</A>.  Returns <C>true</C>, or the
#! <Ref Func="SGV_ReflectionSubgroupInfo"/> record describing the strictly
#! smaller reflection subgroup that the reflections of <A>G</A> actually
#! generate.
DeclareGlobalFunction( "SGV_AssertIsComplexReflectionSubgroup" );
