# Generated by tools/crossref.py -- do not edit by hand.
BindGlobal( "SGV_PaperRefs", rec() );
SGV_PaperRefs.("lem: Type IV C6-pointed cubics") := "Lemma 6.16";
SGV_PaperRefs.("prop:Vtype3") := "Proposition B.10";
SGV_PaperRefs.("subsec:type3-cubic-monodromy") := "Subsection 5.3";
